### ISSUE TITLE
Exploding loss in other datasets

### ISSUE THREAD

**Issue by francotheengineer** [wuga214/Variational-Auto-Encoder#1]
Hi Ga Wu,

I'm implementing a CNN VAE very similar to yours, but I'm experiencing exploding loss. 
Did you ever experience this during your development?

Thanks,

Franco

**Comment by wuga214** [comment]
Hi Franco,

At some point, yes. But I do not recall what raised that problem anymore (some coding bugs).
I would check if the latent standard derivation is pushed to 0 during training first. :)

**Comment by francotheengineer** [comment]
Think I fixed it. Too few convolutional layers it seems with silly (1x1) kernel sizes on a dataset with too much noise.

Thanks!
