### ISSUE TITLE
 Cannot feed value of shape (64, 30000) for Tensor 'vae/Placeholder:0', which has shape '(?, 12288)'

### ISSUE THREAD

**Issue by universefall** [wuga214/Variational-Auto-Encoder#2]
hello，I download  the anime dataset, then preprocess it with providers/anime.py to generate faces.npy, then I run python vae_train_anime.py. However,it doesn't work. it comes with a error"Cannot feed value of shape (64, 30000) for Tensor 'vae/Placeholder:0', which has shape '(?, 12288)'". Is my the shape of the faces.npy wrong? it has the shape of [51223,30000]. Thank you.

**Comment by wuga214** [comment]
Hey, 
Yes, your data is in the wrong shape. The input shape requires to be (?, 12288), which means it accepts **arbitrary batch size** and image with dimension **64 * 64 * 3 = 12288**.

**Comment by universefall** [comment]
> Hey,
> Yes, your data is in the wrong shape. The input shape requires to be (?, 12288), which means it accepts **arbitrary batch size** and image with dimension **64 * 64 * 3 = 12288**.

So，I should resize images to **64 * 64 * 3**. I notice there is a padding operation in your code anime.py
`def _get_data(self, image_folder):

        image_names = getfiles(image_folder)

        images = []

        for image_name in tqdm(image_names):
            image = np.array(Image.open('{0}/{1}'.format(image_folder, image_name)))
            if np.ndim(image) == 3:
                image = (image / 255.) * 2 - 1
                image = np.pad(image, ((2, 2), (2, 2), (0, 0)), mode='constant')
                images.append(image.flatten())

        images = np.array(images)

        return images` 
the generated .npy produce wrong shape.

**Comment by wuga214** [comment]
Aha.. 

That code is used to process a very particular dataset, which was in shape **60 * 60 * 3**
https://github.com/wuga214/IMPLEMENTATION_Wasserstein_GAN_Anime/tree/master/face

If the data is already in right shape, we don't need the padding.

**Comment by universefall** [comment]
I resize the training image to **60 * 60 * 3**. I works! Thank u sooooo much!

**Comment by universefall** [comment]
I try to change the latent dim number to 256 to see its performance.
